//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_contract_owner
    {
        public int id { get; set; }
        public string owner_nip { get; set; }
        public string owner_name { get; set; }
        public Nullable<int> sam { get; set; }
        public string owner_jabatan { get; set; }
        public Nullable<decimal> max_contract_value_allowed { get; set; }
        public string user_name_approval { get; set; }
        public string kode_sub { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
