//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_vendor
    {
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorType { get; set; }
        public string VendorCreated { get; set; }
        public Nullable<System.DateTime> VendorDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VendorCountry { get; set; }
        public string VendorCity { get; set; }
        public string VendorSearchTerm { get; set; }
        public string VendorOldId { get; set; }
        public string VendorCoCd { get; set; }
        public string email { get; set; }
    }
}
