//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_contract
    {
        public string ContractId { get; set; }
        public string ContractNo { get; set; }
        public string NoPR { get; set; }
        public string NoPO { get; set; }
        public string ContractTitle { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string IdVendor { get; set; }
        public string Description { get; set; }
        public string Done { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string ActiveYn { get; set; }
        public Nullable<int> AlertDay { get; set; }
        public Nullable<int> Snooze { get; set; }
    }
}
