//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config_contract_list
    {
        public int Id { get; set; }
        public string Setting { get; set; }
        public string Value { get; set; }
        public string UserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
