//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_cont_alert_dest_mailStakeHolder
    {
        public int Id { get; set; }
        public Nullable<int> SHId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Jabatan { get; set; }
        public string Fungsi { get; set; }
    }
}
