//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_contracts
    {
        public string ContractId { get; set; }
        public string ParentId { get; set; }
        public string CandidateId_1 { get; set; }
        public string CandidateId_2 { get; set; }
        public string CandidateId_3 { get; set; }
        public Nullable<int> ContractGroup { get; set; }
        public string ContractNo { get; set; }
        public string NoPR { get; set; }
        public string NoPO { get; set; }
        public string ContractTitle { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractType { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string IdVendor { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public string Done { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public Nullable<int> AlertDay { get; set; }
        public Nullable<int> Snooze { get; set; }
        public string CorpNamePihak1 { get; set; }
        public string PenanggungJawabPihak1 { get; set; }
        public string JabatanPihak1 { get; set; }
        public string AlamatPihak1 { get; set; }
        public string PhonePihak1 { get; set; }
        public string FaxPihak1 { get; set; }
        public string EmailPihak1 { get; set; }
        public string CorpNamePihak2 { get; set; }
        public string PenanggungJawabPihak2 { get; set; }
        public string JabatanPihak2 { get; set; }
        public string AlamatPihak2 { get; set; }
        public string PhonePihak2 { get; set; }
        public string FaxPihak2 { get; set; }
        public string EmailPihak2 { get; set; }
        public string StrDay { get; set; }
        public string StrMonth { get; set; }
        public string StrYear { get; set; }
        public Nullable<int> InProcess { get; set; }
        public string ApproverPic { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ReceiverPic { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string BankName { get; set; }
        public string VaNo { get; set; }
        public string VaName { get; set; }
        public string StrDate { get; set; }
        public string Fungsi { get; set; }
        public Nullable<System.DateTime> StartProject { get; set; }
        public Nullable<System.DateTime> EndProject { get; set; }
        public string AddendumContractNo { get; set; }
        public Nullable<bool> IsAddendum { get; set; }
        public string ActiveYn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> ProcurementId { get; set; }
    }
}
