//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pengajuan_detail
    {
        public int Id { get; set; }
        public string Pengajuan { get; set; }
        public int Item { get; set; }
        public Nullable<int> RealAsset { get; set; }
        public Nullable<System.DateTime> RealDate { get; set; }
        public string RealUser { get; set; }
    }
}
