//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_proc_procurement
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string Function { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Remark { get; set; }
        public int IsCompleteDoc { get; set; }
        public int Status { get; set; }
        public string Winner { get; set; }
        public Nullable<int> Spmp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public int IsDeleted { get; set; }
        public string NoPR { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<int> Snooze { get; set; }
        public Nullable<System.DateTime> ProcurementDate { get; set; }
        public Nullable<decimal> NegotiationValue { get; set; }
        public string RppSummary { get; set; }
        public string NegotiationSummary { get; set; }
        public string PenunjukanSummary { get; set; }
        public string KesanggupanSummary { get; set; }
    }
}
