//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_proc_rapat_penjelasan
    {
        public int Id { get; set; }
        public int ProcID { get; set; }
        public int ReftID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string EventDay { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public int IsDeleted { get; set; }
    }
}
