//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_contract
    {
        public string ContractId { get; set; }
        public string ContractNo { get; set; }
        public string NoPR { get; set; }
        public string NoPO { get; set; }
        public string ContractTitle { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string ContractDate { get; set; }
        public string ContractType { get; set; }
        public string ContractTypeName { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string IdVendor { get; set; }
        public string VendorName { get; set; }
        public string Description { get; set; }
        public string Done { get; set; }
        public string DoneDate { get; set; }
        public string CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string ActiveYn { get; set; }
        public string DayAlert { get; set; }
        public Nullable<int> DayLeft { get; set; }
        public Nullable<int> Snooze { get; set; }
        public Nullable<int> AlertDay { get; set; }
        public string ContractStatus { get; set; }
    }
}
