//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAsset
    {
        public int recid { get; set; }
        public int AssetId { get; set; }
        public string KodeBarcode { get; set; }
        public string NamaAsset { get; set; }
        public string KodeKategori { get; set; }
        public string NamaKategori { get; set; }
        public string ServiceTag { get; set; }
        public string NoSeri { get; set; }
        public string KodeLokasi { get; set; }
        public string KodeUnit { get; set; }
        public string NamaUnit { get; set; }
        public string KodeFungsi { get; set; }
        public string NamaFungsi { get; set; }
        public string KodePengguna { get; set; }
        public string NamaPengguna { get; set; }
    }
}
