//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPengajuan
    {
        public string Id { get; set; }
        public string DestLocation { get; set; }
        public string DestPengguna { get; set; }
        public string Keterangan { get; set; }
        public Nullable<int> Process { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public string UpdateDate { get; set; }
        public string ActiveYn { get; set; }
        public int GroupPengajuan { get; set; }
        public string ProcessName { get; set; }
        public string HtmlTag { get; set; }
        public string PicProcess { get; set; }
        public string PicAD { get; set; }
        public string USER_AD { get; set; }
        public string FUNGSI { get; set; }
        public string AtasanName { get; set; }
        public string UserAtasan { get; set; }
        public string NamaUnit { get; set; }
        public string NamaPengguna { get; set; }
        public string GroupName { get; set; }
        public string FinnalApprovement { get; set; }
        public string RealisasiPic { get; set; }
        public string CurrentTaskPic { get; set; }
        public string Realized { get; set; }
        public string NoPengajuan { get; set; }
    }
}
