//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPengajuanDetail
    {
        public int recid { get; set; }
        public int Id { get; set; }
        public Nullable<int> ReqId { get; set; }
        public string Pengajuan { get; set; }
        public int Item { get; set; }
        public Nullable<int> RealAsset { get; set; }
        public Nullable<int> RealisasiId { get; set; }
        public Nullable<System.DateTime> RealDate { get; set; }
        public string RealUser { get; set; }
        public string ReqItem { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ReqPart { get; set; }
        public string PartName { get; set; }
        public Nullable<int> ReqQty { get; set; }
        public string ReqKeterangan { get; set; }
        public string ReqType { get; set; }
        public string ReqReason { get; set; }
        public string ReqMerk { get; set; }
        public string ReqNoSeri { get; set; }
        public string KodeBarcode { get; set; }
        public string ReqStatus { get; set; }
    }
}
