//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPengguna
    {
        public long ID { get; set; }
        public string NIP { get; set; }
        public string NM_PEG { get; set; }
        public string NM_UNIT_ORG { get; set; }
        public string FUNGSI { get; set; }
        public string NM_JABATAN_STR { get; set; }
        public string USR_AD { get; set; }
    }
}
