//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRequest
    {
        public int recid { get; set; }
        public int ReqId { get; set; }
        public string ReqItem { get; set; }
        public int ReqType { get; set; }
        public int ReqQty { get; set; }
        public int ReqPart { get; set; }
        public string ReqKeterangan { get; set; }
        public string ReqReason { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<int> ReqGroup { get; set; }
        public string ActiveYn { get; set; }
        public string ItemName { get; set; }
        public string PartName { get; set; }
        public string ReqTypeName { get; set; }
        public string GroupName { get; set; }
    }
}
