//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.ServiceDoc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDoc.ServiceDocSoap")]
    public interface ServiceDocSoap {
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile3", ReplyAction="*")]
        I_Care.ServiceDoc.PutFile3Response PutFile3(I_Care.ServiceDoc.PutFile3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile3", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile3Response> PutFile3Async(I_Care.ServiceDoc.PutFile3Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile2", ReplyAction="*")]
        I_Care.ServiceDoc.PutFile2Response PutFile2(I_Care.ServiceDoc.PutFile2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile2", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile2Response> PutFile2Async(I_Care.ServiceDoc.PutFile2Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        I_Care.ServiceDoc.PutFileResponse PutFile(I_Care.ServiceDoc.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFileResponse> PutFileAsync(I_Care.ServiceDoc.PutFileRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileId", ReplyAction="*")]
        I_Care.ServiceDoc.GetFileIdResponse GetFileId(I_Care.ServiceDoc.GetFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileId", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileIdResponse> GetFileIdAsync(I_Care.ServiceDoc.GetFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData2", ReplyAction="*")]
        I_Care.ServiceDoc.GetFileData2Response GetFileData2(I_Care.ServiceDoc.GetFileData2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData2", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileData2Response> GetFileData2Async(I_Care.ServiceDoc.GetFileData2Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        I_Care.ServiceDoc.GetFileDataResponse GetFileData(I_Care.ServiceDoc.GetFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataResponse> GetFileDataAsync(I_Care.ServiceDoc.GetFileDataRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDataById", ReplyAction="*")]
        I_Care.ServiceDoc.GetFileDataByIdResponse GetFileDataById(I_Care.ServiceDoc.GetFileDataByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDataById", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataByIdResponse> GetFileDataByIdAsync(I_Care.ServiceDoc.GetFileDataByIdRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        I_Care.ServiceDoc.DeleteFileResponse DeleteFile(I_Care.ServiceDoc.DeleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileResponse> DeleteFileAsync(I_Care.ServiceDoc.DeleteFileRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFileById", ReplyAction="*")]
        I_Care.ServiceDoc.DeleteFileByIdResponse DeleteFileById(I_Care.ServiceDoc.DeleteFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileByIdResponse> DeleteFileByIdAsync(I_Care.ServiceDoc.DeleteFileByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilePreById", ReplyAction="*")]
        I_Care.ServiceDoc.DeleteFilePreByIdResponse DeleteFilePreById(I_Care.ServiceDoc.DeleteFilePreByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilePreById", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(I_Care.ServiceDoc.DeleteFilePreByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveFileById", ReplyAction="*")]
        I_Care.ServiceDoc.MoveFileByIdResponse MoveFileById(I_Care.ServiceDoc.MoveFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.MoveFileByIdResponse> MoveFileByIdAsync(I_Care.ServiceDoc.MoveFileByIdRequest request);
        
        // CODEGEN: Generating message contract since element name JsonID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMergePdfFile", ReplyAction="*")]
        I_Care.ServiceDoc.GetMergePdfFileResponse GetMergePdfFile(I_Care.ServiceDoc.GetMergePdfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMergePdfFile", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetMergePdfFileResponse> GetMergePdfFileAsync(I_Care.ServiceDoc.GetMergePdfFileRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Organize", ReplyAction="*")]
        I_Care.ServiceDoc.OrganizeResponse Organize(I_Care.ServiceDoc.OrganizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Organize", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.OrganizeResponse> OrganizeAsync(I_Care.ServiceDoc.OrganizeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFile3RequestBody Body;
        
        public PutFile3Request() {
        }
        
        public PutFile3Request(I_Care.ServiceDoc.PutFile3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile3RequestBody() {
        }
        
        public PutFile3RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3Response", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFile3ResponseBody Body;
        
        public PutFile3Response() {
        }
        
        public PutFile3Response(I_Care.ServiceDoc.PutFile3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile3Result;
        
        public PutFile3ResponseBody() {
        }
        
        public PutFile3ResponseBody(string PutFile3Result) {
            this.PutFile3Result = PutFile3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFile2RequestBody Body;
        
        public PutFile2Request() {
        }
        
        public PutFile2Request(I_Care.ServiceDoc.PutFile2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile2RequestBody() {
        }
        
        public PutFile2RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2Response", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFile2ResponseBody Body;
        
        public PutFile2Response() {
        }
        
        public PutFile2Response(I_Care.ServiceDoc.PutFile2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile2Result;
        
        public PutFile2ResponseBody() {
        }
        
        public PutFile2ResponseBody(string PutFile2Result) {
            this.PutFile2Result = PutFile2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFileRequestBody Body;
        
        public PutFileRequest() {
        }
        
        public PutFileRequest(I_Care.ServiceDoc.PutFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        public PutFileRequestBody() {
        }
        
        public PutFileRequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.PutFileResponseBody Body;
        
        public PutFileResponse() {
        }
        
        public PutFileResponse(I_Care.ServiceDoc.PutFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFileResult;
        
        public PutFileResponseBody() {
        }
        
        public PutFileResponseBody(string PutFileResult) {
            this.PutFileResult = PutFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileId", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileIdRequestBody Body;
        
        public GetFileIdRequest() {
        }
        
        public GetFileIdRequest(I_Care.ServiceDoc.GetFileIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileIdRequestBody() {
        }
        
        public GetFileIdRequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileIdResponseBody Body;
        
        public GetFileIdResponse() {
        }
        
        public GetFileIdResponse(I_Care.ServiceDoc.GetFileIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetFileIdResult;
        
        public GetFileIdResponseBody() {
        }
        
        public GetFileIdResponseBody(int GetFileIdResult) {
            this.GetFileIdResult = GetFileIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileData2RequestBody Body;
        
        public GetFileData2Request() {
        }
        
        public GetFileData2Request(I_Care.ServiceDoc.GetFileData2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileData2RequestBody() {
        }
        
        public GetFileData2RequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2Response", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileData2ResponseBody Body;
        
        public GetFileData2Response() {
        }
        
        public GetFileData2Response(I_Care.ServiceDoc.GetFileData2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileData2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentType;
        
        public GetFileData2ResponseBody() {
        }
        
        public GetFileData2ResponseBody(byte[] GetFileData2Result, string contentType) {
            this.GetFileData2Result = GetFileData2Result;
            this.contentType = contentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileDataRequestBody Body;
        
        public GetFileDataRequest() {
        }
        
        public GetFileDataRequest(I_Care.ServiceDoc.GetFileDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileDataRequestBody() {
        }
        
        public GetFileDataRequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileDataResponseBody Body;
        
        public GetFileDataResponse() {
        }
        
        public GetFileDataResponse(I_Care.ServiceDoc.GetFileDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataResult;
        
        public GetFileDataResponseBody() {
        }
        
        public GetFileDataResponseBody(byte[] GetFileDataResult) {
            this.GetFileDataResult = GetFileDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataById", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileDataByIdRequestBody Body;
        
        public GetFileDataByIdRequest() {
        }
        
        public GetFileDataByIdRequest(I_Care.ServiceDoc.GetFileDataByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetFileDataByIdRequestBody() {
        }
        
        public GetFileDataByIdRequestBody(int Id, string username, string password) {
            this.Id = Id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetFileDataByIdResponseBody Body;
        
        public GetFileDataByIdResponse() {
        }
        
        public GetFileDataByIdResponse(I_Care.ServiceDoc.GetFileDataByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataByIdResult;
        
        public GetFileDataByIdResponseBody() {
        }
        
        public GetFileDataByIdResponseBody(byte[] GetFileDataByIdResult) {
            this.GetFileDataByIdResult = GetFileDataByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFile", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFileRequestBody Body;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(I_Care.ServiceDoc.DeleteFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string delUser;
        
        public DeleteFileRequestBody() {
        }
        
        public DeleteFileRequestBody(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFileResponseBody Body;
        
        public DeleteFileResponse() {
        }
        
        public DeleteFileResponse(I_Care.ServiceDoc.DeleteFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileResult;
        
        public DeleteFileResponseBody() {
        }
        
        public DeleteFileResponseBody(string DeleteFileResult) {
            this.DeleteFileResult = DeleteFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileById", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFileByIdRequestBody Body;
        
        public DeleteFileByIdRequest() {
        }
        
        public DeleteFileByIdRequest(I_Care.ServiceDoc.DeleteFileByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFileByIdRequestBody() {
        }
        
        public DeleteFileByIdRequestBody(int Id, string username, string password, string delUser) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFileByIdResponseBody Body;
        
        public DeleteFileByIdResponse() {
        }
        
        public DeleteFileByIdResponse(I_Care.ServiceDoc.DeleteFileByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileByIdResult;
        
        public DeleteFileByIdResponseBody() {
        }
        
        public DeleteFileByIdResponseBody(string DeleteFileByIdResult) {
            this.DeleteFileByIdResult = DeleteFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreById", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFilePreByIdRequestBody Body;
        
        public DeleteFilePreByIdRequest() {
        }
        
        public DeleteFilePreByIdRequest(I_Care.ServiceDoc.DeleteFilePreByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFilePreByIdRequestBody() {
        }
        
        public DeleteFilePreByIdRequestBody(int Id, string username, string password, string delUser) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.DeleteFilePreByIdResponseBody Body;
        
        public DeleteFilePreByIdResponse() {
        }
        
        public DeleteFilePreByIdResponse(I_Care.ServiceDoc.DeleteFilePreByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFilePreByIdResult;
        
        public DeleteFilePreByIdResponseBody() {
        }
        
        public DeleteFilePreByIdResponseBody(string DeleteFilePreByIdResult) {
            this.DeleteFilePreByIdResult = DeleteFilePreByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileById", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.MoveFileByIdRequestBody Body;
        
        public MoveFileByIdRequest() {
        }
        
        public MoveFileByIdRequest(I_Care.ServiceDoc.MoveFileByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OldKey2;
        
        public MoveFileByIdRequestBody() {
        }
        
        public MoveFileByIdRequestBody(int Id, string username, string password, string delUser, string OldKey2) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
            this.OldKey2 = OldKey2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.MoveFileByIdResponseBody Body;
        
        public MoveFileByIdResponse() {
        }
        
        public MoveFileByIdResponse(I_Care.ServiceDoc.MoveFileByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MoveFileByIdResult;
        
        public MoveFileByIdResponseBody() {
        }
        
        public MoveFileByIdResponseBody(string MoveFileByIdResult) {
            this.MoveFileByIdResult = MoveFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFile", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetMergePdfFileRequestBody Body;
        
        public GetMergePdfFileRequest() {
        }
        
        public GetMergePdfFileRequest(I_Care.ServiceDoc.GetMergePdfFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetMergePdfFileRequestBody() {
        }
        
        public GetMergePdfFileRequestBody(string JsonID, string username, string password) {
            this.JsonID = JsonID;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.GetMergePdfFileResponseBody Body;
        
        public GetMergePdfFileResponse() {
        }
        
        public GetMergePdfFileResponse(I_Care.ServiceDoc.GetMergePdfFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMergePdfFileResult;
        
        public GetMergePdfFileResponseBody() {
        }
        
        public GetMergePdfFileResponseBody(byte[] GetMergePdfFileResult) {
            this.GetMergePdfFileResult = GetMergePdfFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Organize", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.OrganizeRequestBody Body;
        
        public OrganizeRequest() {
        }
        
        public OrganizeRequest(I_Care.ServiceDoc.OrganizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        public OrganizeRequestBody() {
        }
        
        public OrganizeRequestBody(string source) {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrganizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public I_Care.ServiceDoc.OrganizeResponseBody Body;
        
        public OrganizeResponse() {
        }
        
        public OrganizeResponse(I_Care.ServiceDoc.OrganizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OrganizeResult;
        
        public OrganizeResponseBody() {
        }
        
        public OrganizeResponseBody(int OrganizeResult) {
            this.OrganizeResult = OrganizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDocSoapChannel : I_Care.ServiceDoc.ServiceDocSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDocSoapClient : System.ServiceModel.ClientBase<I_Care.ServiceDoc.ServiceDocSoap>, I_Care.ServiceDoc.ServiceDocSoap {
        
        public ServiceDocSoapClient() {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.PutFile3Response I_Care.ServiceDoc.ServiceDocSoap.PutFile3(I_Care.ServiceDoc.PutFile3Request request) {
            return base.Channel.PutFile3(request);
        }
        
        public string PutFile3(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            I_Care.ServiceDoc.PutFile3Request inValue = new I_Care.ServiceDoc.PutFile3Request();
            inValue.Body = new I_Care.ServiceDoc.PutFile3RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            I_Care.ServiceDoc.PutFile3Response retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFile3(inValue);
            return retVal.Body.PutFile3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile3Response> I_Care.ServiceDoc.ServiceDocSoap.PutFile3Async(I_Care.ServiceDoc.PutFile3Request request) {
            return base.Channel.PutFile3Async(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile3Response> PutFile3Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            I_Care.ServiceDoc.PutFile3Request inValue = new I_Care.ServiceDoc.PutFile3Request();
            inValue.Body = new I_Care.ServiceDoc.PutFile3RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFile3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.PutFile2Response I_Care.ServiceDoc.ServiceDocSoap.PutFile2(I_Care.ServiceDoc.PutFile2Request request) {
            return base.Channel.PutFile2(request);
        }
        
        public string PutFile2(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            I_Care.ServiceDoc.PutFile2Request inValue = new I_Care.ServiceDoc.PutFile2Request();
            inValue.Body = new I_Care.ServiceDoc.PutFile2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            I_Care.ServiceDoc.PutFile2Response retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFile2(inValue);
            return retVal.Body.PutFile2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile2Response> I_Care.ServiceDoc.ServiceDocSoap.PutFile2Async(I_Care.ServiceDoc.PutFile2Request request) {
            return base.Channel.PutFile2Async(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFile2Response> PutFile2Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            I_Care.ServiceDoc.PutFile2Request inValue = new I_Care.ServiceDoc.PutFile2Request();
            inValue.Body = new I_Care.ServiceDoc.PutFile2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFile2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.PutFileResponse I_Care.ServiceDoc.ServiceDocSoap.PutFile(I_Care.ServiceDoc.PutFileRequest request) {
            return base.Channel.PutFile(request);
        }
        
        public string PutFile(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            I_Care.ServiceDoc.PutFileRequest inValue = new I_Care.ServiceDoc.PutFileRequest();
            inValue.Body = new I_Care.ServiceDoc.PutFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            I_Care.ServiceDoc.PutFileResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFile(inValue);
            return retVal.Body.PutFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFileResponse> I_Care.ServiceDoc.ServiceDocSoap.PutFileAsync(I_Care.ServiceDoc.PutFileRequest request) {
            return base.Channel.PutFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.PutFileResponse> PutFileAsync(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            I_Care.ServiceDoc.PutFileRequest inValue = new I_Care.ServiceDoc.PutFileRequest();
            inValue.Body = new I_Care.ServiceDoc.PutFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).PutFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.GetFileIdResponse I_Care.ServiceDoc.ServiceDocSoap.GetFileId(I_Care.ServiceDoc.GetFileIdRequest request) {
            return base.Channel.GetFileId(request);
        }
        
        public int GetFileId(string source, string key1, string key2, int key3, int key4, int revision) {
            I_Care.ServiceDoc.GetFileIdRequest inValue = new I_Care.ServiceDoc.GetFileIdRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileIdRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            I_Care.ServiceDoc.GetFileIdResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileId(inValue);
            return retVal.Body.GetFileIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileIdResponse> I_Care.ServiceDoc.ServiceDocSoap.GetFileIdAsync(I_Care.ServiceDoc.GetFileIdRequest request) {
            return base.Channel.GetFileIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileIdResponse> GetFileIdAsync(string source, string key1, string key2, int key3, int key4, int revision) {
            I_Care.ServiceDoc.GetFileIdRequest inValue = new I_Care.ServiceDoc.GetFileIdRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileIdRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.GetFileData2Response I_Care.ServiceDoc.ServiceDocSoap.GetFileData2(I_Care.ServiceDoc.GetFileData2Request request) {
            return base.Channel.GetFileData2(request);
        }
        
        public byte[] GetFileData2(string source, string key1, string key2, int key3, int key4, int revision, out string contentType) {
            I_Care.ServiceDoc.GetFileData2Request inValue = new I_Care.ServiceDoc.GetFileData2Request();
            inValue.Body = new I_Care.ServiceDoc.GetFileData2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            I_Care.ServiceDoc.GetFileData2Response retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileData2(inValue);
            contentType = retVal.Body.contentType;
            return retVal.Body.GetFileData2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileData2Response> I_Care.ServiceDoc.ServiceDocSoap.GetFileData2Async(I_Care.ServiceDoc.GetFileData2Request request) {
            return base.Channel.GetFileData2Async(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileData2Response> GetFileData2Async(string source, string key1, string key2, int key3, int key4, int revision) {
            I_Care.ServiceDoc.GetFileData2Request inValue = new I_Care.ServiceDoc.GetFileData2Request();
            inValue.Body = new I_Care.ServiceDoc.GetFileData2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileData2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.GetFileDataResponse I_Care.ServiceDoc.ServiceDocSoap.GetFileData(I_Care.ServiceDoc.GetFileDataRequest request) {
            return base.Channel.GetFileData(request);
        }
        
        public byte[] GetFileData(string source, string key1, string key2, int key3, int key4, int revision) {
            I_Care.ServiceDoc.GetFileDataRequest inValue = new I_Care.ServiceDoc.GetFileDataRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileDataRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            I_Care.ServiceDoc.GetFileDataResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileData(inValue);
            return retVal.Body.GetFileDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataResponse> I_Care.ServiceDoc.ServiceDocSoap.GetFileDataAsync(I_Care.ServiceDoc.GetFileDataRequest request) {
            return base.Channel.GetFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataResponse> GetFileDataAsync(string source, string key1, string key2, int key3, int key4, int revision) {
            I_Care.ServiceDoc.GetFileDataRequest inValue = new I_Care.ServiceDoc.GetFileDataRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileDataRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.GetFileDataByIdResponse I_Care.ServiceDoc.ServiceDocSoap.GetFileDataById(I_Care.ServiceDoc.GetFileDataByIdRequest request) {
            return base.Channel.GetFileDataById(request);
        }
        
        public byte[] GetFileDataById(int Id, string username, string password) {
            I_Care.ServiceDoc.GetFileDataByIdRequest inValue = new I_Care.ServiceDoc.GetFileDataByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileDataByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            I_Care.ServiceDoc.GetFileDataByIdResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileDataById(inValue);
            return retVal.Body.GetFileDataByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataByIdResponse> I_Care.ServiceDoc.ServiceDocSoap.GetFileDataByIdAsync(I_Care.ServiceDoc.GetFileDataByIdRequest request) {
            return base.Channel.GetFileDataByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.GetFileDataByIdResponse> GetFileDataByIdAsync(int Id, string username, string password) {
            I_Care.ServiceDoc.GetFileDataByIdRequest inValue = new I_Care.ServiceDoc.GetFileDataByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.GetFileDataByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetFileDataByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.DeleteFileResponse I_Care.ServiceDoc.ServiceDocSoap.DeleteFile(I_Care.ServiceDoc.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public string DeleteFile(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            I_Care.ServiceDoc.DeleteFileRequest inValue = new I_Care.ServiceDoc.DeleteFileRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            inValue.Body.delUser = delUser;
            I_Care.ServiceDoc.DeleteFileResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFile(inValue);
            return retVal.Body.DeleteFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileResponse> I_Care.ServiceDoc.ServiceDocSoap.DeleteFileAsync(I_Care.ServiceDoc.DeleteFileRequest request) {
            return base.Channel.DeleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileResponse> DeleteFileAsync(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            I_Care.ServiceDoc.DeleteFileRequest inValue = new I_Care.ServiceDoc.DeleteFileRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            inValue.Body.delUser = delUser;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.DeleteFileByIdResponse I_Care.ServiceDoc.ServiceDocSoap.DeleteFileById(I_Care.ServiceDoc.DeleteFileByIdRequest request) {
            return base.Channel.DeleteFileById(request);
        }
        
        public string DeleteFileById(int Id, string username, string password, string delUser) {
            I_Care.ServiceDoc.DeleteFileByIdRequest inValue = new I_Care.ServiceDoc.DeleteFileByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            I_Care.ServiceDoc.DeleteFileByIdResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFileById(inValue);
            return retVal.Body.DeleteFileByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileByIdResponse> I_Care.ServiceDoc.ServiceDocSoap.DeleteFileByIdAsync(I_Care.ServiceDoc.DeleteFileByIdRequest request) {
            return base.Channel.DeleteFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFileByIdResponse> DeleteFileByIdAsync(int Id, string username, string password, string delUser) {
            I_Care.ServiceDoc.DeleteFileByIdRequest inValue = new I_Care.ServiceDoc.DeleteFileByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.DeleteFilePreByIdResponse I_Care.ServiceDoc.ServiceDocSoap.DeleteFilePreById(I_Care.ServiceDoc.DeleteFilePreByIdRequest request) {
            return base.Channel.DeleteFilePreById(request);
        }
        
        public string DeleteFilePreById(int Id, string username, string password, string delUser) {
            I_Care.ServiceDoc.DeleteFilePreByIdRequest inValue = new I_Care.ServiceDoc.DeleteFilePreByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFilePreByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            I_Care.ServiceDoc.DeleteFilePreByIdResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFilePreById(inValue);
            return retVal.Body.DeleteFilePreByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFilePreByIdResponse> I_Care.ServiceDoc.ServiceDocSoap.DeleteFilePreByIdAsync(I_Care.ServiceDoc.DeleteFilePreByIdRequest request) {
            return base.Channel.DeleteFilePreByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(int Id, string username, string password, string delUser) {
            I_Care.ServiceDoc.DeleteFilePreByIdRequest inValue = new I_Care.ServiceDoc.DeleteFilePreByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.DeleteFilePreByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).DeleteFilePreByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.MoveFileByIdResponse I_Care.ServiceDoc.ServiceDocSoap.MoveFileById(I_Care.ServiceDoc.MoveFileByIdRequest request) {
            return base.Channel.MoveFileById(request);
        }
        
        public string MoveFileById(int Id, string username, string password, string delUser, string OldKey2) {
            I_Care.ServiceDoc.MoveFileByIdRequest inValue = new I_Care.ServiceDoc.MoveFileByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.MoveFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            inValue.Body.OldKey2 = OldKey2;
            I_Care.ServiceDoc.MoveFileByIdResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).MoveFileById(inValue);
            return retVal.Body.MoveFileByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.MoveFileByIdResponse> I_Care.ServiceDoc.ServiceDocSoap.MoveFileByIdAsync(I_Care.ServiceDoc.MoveFileByIdRequest request) {
            return base.Channel.MoveFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.MoveFileByIdResponse> MoveFileByIdAsync(int Id, string username, string password, string delUser, string OldKey2) {
            I_Care.ServiceDoc.MoveFileByIdRequest inValue = new I_Care.ServiceDoc.MoveFileByIdRequest();
            inValue.Body = new I_Care.ServiceDoc.MoveFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            inValue.Body.OldKey2 = OldKey2;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).MoveFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.GetMergePdfFileResponse I_Care.ServiceDoc.ServiceDocSoap.GetMergePdfFile(I_Care.ServiceDoc.GetMergePdfFileRequest request) {
            return base.Channel.GetMergePdfFile(request);
        }
        
        public byte[] GetMergePdfFile(string JsonID, string username, string password) {
            I_Care.ServiceDoc.GetMergePdfFileRequest inValue = new I_Care.ServiceDoc.GetMergePdfFileRequest();
            inValue.Body = new I_Care.ServiceDoc.GetMergePdfFileRequestBody();
            inValue.Body.JsonID = JsonID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            I_Care.ServiceDoc.GetMergePdfFileResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetMergePdfFile(inValue);
            return retVal.Body.GetMergePdfFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.GetMergePdfFileResponse> I_Care.ServiceDoc.ServiceDocSoap.GetMergePdfFileAsync(I_Care.ServiceDoc.GetMergePdfFileRequest request) {
            return base.Channel.GetMergePdfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.GetMergePdfFileResponse> GetMergePdfFileAsync(string JsonID, string username, string password) {
            I_Care.ServiceDoc.GetMergePdfFileRequest inValue = new I_Care.ServiceDoc.GetMergePdfFileRequest();
            inValue.Body = new I_Care.ServiceDoc.GetMergePdfFileRequestBody();
            inValue.Body.JsonID = JsonID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).GetMergePdfFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceDoc.OrganizeResponse I_Care.ServiceDoc.ServiceDocSoap.Organize(I_Care.ServiceDoc.OrganizeRequest request) {
            return base.Channel.Organize(request);
        }
        
        public int Organize(string source) {
            I_Care.ServiceDoc.OrganizeRequest inValue = new I_Care.ServiceDoc.OrganizeRequest();
            inValue.Body = new I_Care.ServiceDoc.OrganizeRequestBody();
            inValue.Body.source = source;
            I_Care.ServiceDoc.OrganizeResponse retVal = ((I_Care.ServiceDoc.ServiceDocSoap)(this)).Organize(inValue);
            return retVal.Body.OrganizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceDoc.OrganizeResponse> I_Care.ServiceDoc.ServiceDocSoap.OrganizeAsync(I_Care.ServiceDoc.OrganizeRequest request) {
            return base.Channel.OrganizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceDoc.OrganizeResponse> OrganizeAsync(string source) {
            I_Care.ServiceDoc.OrganizeRequest inValue = new I_Care.ServiceDoc.OrganizeRequest();
            inValue.Body = new I_Care.ServiceDoc.OrganizeRequestBody();
            inValue.Body.source = source;
            return ((I_Care.ServiceDoc.ServiceDocSoap)(this)).OrganizeAsync(inValue);
        }
    }
}
