//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Care.ServiceSSO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateResult", Namespace="SSO")]
    [System.SerializableAttribute()]
    public partial class ValidateResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ValidateUserResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ValidateUserResult {
            get {
                return this.ValidateUserResultField;
            }
            set {
                if ((this.ValidateUserResultField.Equals(value) != true)) {
                    this.ValidateUserResultField = value;
                    this.RaisePropertyChanged("ValidateUserResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NIP {
            get {
                return this.NIPField;
            }
            set {
                if ((object.ReferenceEquals(this.NIPField, value) != true)) {
                    this.NIPField = value;
                    this.RaisePropertyChanged("NIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="SSO", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SSO", ConfigurationName="ServiceSSO.SSOWSSoap")]
    public interface SSOWSSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUser", ReplyAction="*")]
        I_Care.ServiceSSO.ValidateUserResponse ValidateUser(I_Care.ServiceSSO.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserResponse> ValidateUserAsync(I_Care.ServiceSSO.ValidateUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUserGetNIP", ReplyAction="*")]
        I_Care.ServiceSSO.ValidateUserGetNIPResponse ValidateUserGetNIP(I_Care.ServiceSSO.ValidateUserGetNIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUserGetNIP", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(I_Care.ServiceSSO.ValidateUserGetNIPRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/Verify", ReplyAction="*")]
        I_Care.ServiceSSO.VerifyResponse Verify(I_Care.ServiceSSO.VerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/Verify", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.VerifyResponse> VerifyAsync(I_Care.ServiceSSO.VerifyRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnit", ReplyAction="*")]
        I_Care.ServiceSSO.GetUserUnitResponse GetUserUnit(I_Care.ServiceSSO.GetUserUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitResponse> GetUserUnitAsync(I_Care.ServiceSSO.GetUserUnitRequest request);
        
        // CODEGEN: Generating message contract since element name appName from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllRoles", ReplyAction="*")]
        I_Care.ServiceSSO.GetAllRolesResponse GetAllRoles(I_Care.ServiceSSO.GetAllRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllRolesResponse> GetAllRolesAsync(I_Care.ServiceSSO.GetAllRolesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetRolesForUser", ReplyAction="*")]
        I_Care.ServiceSSO.GetRolesForUserResponse GetRolesForUser(I_Care.ServiceSSO.GetRolesForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetRolesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetRolesForUserResponse> GetRolesForUserAsync(I_Care.ServiceSSO.GetRolesForUserRequest request);
        
        // CODEGEN: Generating message contract since element name appName from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUsersInRole", ReplyAction="*")]
        I_Care.ServiceSSO.GetUsersInRoleResponse GetUsersInRole(I_Care.ServiceSSO.GetUsersInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUsersInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(I_Care.ServiceSSO.GetUsersInRoleRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/IsUserInRole", ReplyAction="*")]
        I_Care.ServiceSSO.IsUserInRoleResponse IsUserInRole(I_Care.ServiceSSO.IsUserInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/IsUserInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.IsUserInRoleResponse> IsUserInRoleAsync(I_Care.ServiceSSO.IsUserInRoleRequest request);
        
        // CODEGEN: Generating message contract since element name appName from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/RoleExists", ReplyAction="*")]
        I_Care.ServiceSSO.RoleExistsResponse RoleExists(I_Care.ServiceSSO.RoleExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/RoleExists", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.RoleExistsResponse> RoleExistsAsync(I_Care.ServiceSSO.RoleExistsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/DeleteToken", ReplyAction="*")]
        I_Care.ServiceSSO.DeleteTokenResponse DeleteToken(I_Care.ServiceSSO.DeleteTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/DeleteToken", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.DeleteTokenResponse> DeleteTokenAsync(I_Care.ServiceSSO.DeleteTokenRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccessForUser", ReplyAction="*")]
        I_Care.ServiceSSO.GetAccessForUserResponse GetAccessForUser(I_Care.ServiceSSO.GetAccessForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccessForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccessForUserResponse> GetAccessForUserAsync(I_Care.ServiceSSO.GetAccessForUserRequest request);
        
        // CODEGEN: Generating message contract since element name OdlPass from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ChangePassword", ReplyAction="*")]
        I_Care.ServiceSSO.ChangePasswordResponse ChangePassword(I_Care.ServiceSSO.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ChangePasswordResponse> ChangePasswordAsync(I_Care.ServiceSSO.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name userid from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserType", ReplyAction="*")]
        I_Care.ServiceSSO.GetUserTypeResponse GetUserType(I_Care.ServiceSSO.GetUserTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserType", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserTypeResponse> GetUserTypeAsync(I_Care.ServiceSSO.GetUserTypeRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllowModul", ReplyAction="*")]
        I_Care.ServiceSSO.GetAllowModulResponse GetAllowModul(I_Care.ServiceSSO.GetAllowModulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllowModul", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllowModulResponse> GetAllowModulAsync(I_Care.ServiceSSO.GetAllowModulRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccesExtend", ReplyAction="*")]
        I_Care.ServiceSSO.GetAccesExtendResponse GetAccesExtend(I_Care.ServiceSSO.GetAccesExtendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccesExtend", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccesExtendResponse> GetAccesExtendAsync(I_Care.ServiceSSO.GetAccesExtendRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/CheckAccGroupUser", ReplyAction="*")]
        I_Care.ServiceSSO.CheckAccGroupUserResponse CheckAccGroupUser(I_Care.ServiceSSO.CheckAccGroupUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/CheckAccGroupUser", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(I_Care.ServiceSSO.CheckAccGroupUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SSO is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnitV2", ReplyAction="*")]
        I_Care.ServiceSSO.GetUserUnitV2Response GetUserUnitV2(I_Care.ServiceSSO.GetUserUnitV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnitV2", ReplyAction="*")]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitV2Response> GetUserUnitV2Async(I_Care.ServiceSSO.GetUserUnitV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ValidateUserRequestBody Body;
        
        public ValidateUserRequest() {
        }
        
        public ValidateUserRequest(I_Care.ServiceSSO.ValidateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserRequestBody() {
        }
        
        public ValidateUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ValidateUserResponseBody Body;
        
        public ValidateUserResponse() {
        }
        
        public ValidateUserResponse(I_Care.ServiceSSO.ValidateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponseBody() {
        }
        
        public ValidateUserResponseBody(bool ValidateUserResult) {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIP", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ValidateUserGetNIPRequestBody Body;
        
        public ValidateUserGetNIPRequest() {
        }
        
        public ValidateUserGetNIPRequest(I_Care.ServiceSSO.ValidateUserGetNIPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserGetNIPRequestBody() {
        }
        
        public ValidateUserGetNIPRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIPResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ValidateUserGetNIPResponseBody Body;
        
        public ValidateUserGetNIPResponse() {
        }
        
        public ValidateUserGetNIPResponse(I_Care.ServiceSSO.ValidateUserGetNIPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public I_Care.ServiceSSO.ValidateResult ValidateUserGetNIPResult;
        
        public ValidateUserGetNIPResponseBody() {
        }
        
        public ValidateUserGetNIPResponseBody(I_Care.ServiceSSO.ValidateResult ValidateUserGetNIPResult) {
            this.ValidateUserGetNIPResult = ValidateUserGetNIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.VerifyRequestBody Body;
        
        public VerifyRequest() {
        }
        
        public VerifyRequest(I_Care.ServiceSSO.VerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public VerifyRequestBody() {
        }
        
        public VerifyRequestBody(string username, string token) {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.VerifyResponseBody Body;
        
        public VerifyResponse() {
        }
        
        public VerifyResponse(I_Care.ServiceSSO.VerifyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyResult;
        
        public VerifyResponseBody() {
        }
        
        public VerifyResponseBody(bool VerifyResult) {
            this.VerifyResult = VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnit", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserUnitRequestBody Body;
        
        public GetUserUnitRequest() {
        }
        
        public GetUserUnitRequest(I_Care.ServiceSSO.GetUserUnitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitRequestBody() {
        }
        
        public GetUserUnitRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserUnitResponseBody Body;
        
        public GetUserUnitResponse() {
        }
        
        public GetUserUnitResponse(I_Care.ServiceSSO.GetUserUnitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitResult;
        
        public GetUserUnitResponseBody() {
        }
        
        public GetUserUnitResponseBody(string GetUserUnitResult) {
            this.GetUserUnitResult = GetUserUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoles", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAllRolesRequestBody Body;
        
        public GetAllRolesRequest() {
        }
        
        public GetAllRolesRequest(I_Care.ServiceSSO.GetAllRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public GetAllRolesRequestBody() {
        }
        
        public GetAllRolesRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRolesResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAllRolesResponseBody Body;
        
        public GetAllRolesResponse() {
        }
        
        public GetAllRolesResponse(I_Care.ServiceSSO.GetAllRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public I_Care.ServiceSSO.ArrayOfString GetAllRolesResult;
        
        public GetAllRolesResponseBody() {
        }
        
        public GetAllRolesResponseBody(I_Care.ServiceSSO.ArrayOfString GetAllRolesResult) {
            this.GetAllRolesResult = GetAllRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUser", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetRolesForUserRequestBody Body;
        
        public GetRolesForUserRequest() {
        }
        
        public GetRolesForUserRequest(I_Care.ServiceSSO.GetRolesForUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        public GetRolesForUserRequestBody() {
        }
        
        public GetRolesForUserRequestBody(string username, string appName) {
            this.username = username;
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUserResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetRolesForUserResponseBody Body;
        
        public GetRolesForUserResponse() {
        }
        
        public GetRolesForUserResponse(I_Care.ServiceSSO.GetRolesForUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public I_Care.ServiceSSO.ArrayOfString GetRolesForUserResult;
        
        public GetRolesForUserResponseBody() {
        }
        
        public GetRolesForUserResponseBody(I_Care.ServiceSSO.ArrayOfString GetRolesForUserResult) {
            this.GetRolesForUserResult = GetRolesForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRole", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUsersInRoleRequestBody Body;
        
        public GetUsersInRoleRequest() {
        }
        
        public GetUsersInRoleRequest(I_Care.ServiceSSO.GetUsersInRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public GetUsersInRoleRequestBody() {
        }
        
        public GetUsersInRoleRequestBody(string appName, string roleName) {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRoleResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUsersInRoleResponseBody Body;
        
        public GetUsersInRoleResponse() {
        }
        
        public GetUsersInRoleResponse(I_Care.ServiceSSO.GetUsersInRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public I_Care.ServiceSSO.ArrayOfString GetUsersInRoleResult;
        
        public GetUsersInRoleResponseBody() {
        }
        
        public GetUsersInRoleResponseBody(I_Care.ServiceSSO.ArrayOfString GetUsersInRoleResult) {
            this.GetUsersInRoleResult = GetUsersInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRole", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.IsUserInRoleRequestBody Body;
        
        public IsUserInRoleRequest() {
        }
        
        public IsUserInRoleRequest(I_Care.ServiceSSO.IsUserInRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roleName;
        
        public IsUserInRoleRequestBody() {
        }
        
        public IsUserInRoleRequestBody(string username, string appName, string roleName) {
            this.username = username;
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRoleResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.IsUserInRoleResponseBody Body;
        
        public IsUserInRoleResponse() {
        }
        
        public IsUserInRoleResponse(I_Care.ServiceSSO.IsUserInRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserInRoleResult;
        
        public IsUserInRoleResponseBody() {
        }
        
        public IsUserInRoleResponseBody(bool IsUserInRoleResult) {
            this.IsUserInRoleResult = IsUserInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExists", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.RoleExistsRequestBody Body;
        
        public RoleExistsRequest() {
        }
        
        public RoleExistsRequest(I_Care.ServiceSSO.RoleExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public RoleExistsRequestBody() {
        }
        
        public RoleExistsRequestBody(string appName, string roleName) {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExistsResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.RoleExistsResponseBody Body;
        
        public RoleExistsResponse() {
        }
        
        public RoleExistsResponse(I_Care.ServiceSSO.RoleExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RoleExistsResult;
        
        public RoleExistsResponseBody() {
        }
        
        public RoleExistsResponseBody(bool RoleExistsResult) {
            this.RoleExistsResult = RoleExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToken", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.DeleteTokenRequestBody Body;
        
        public DeleteTokenRequest() {
        }
        
        public DeleteTokenRequest(I_Care.ServiceSSO.DeleteTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class DeleteTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public DeleteTokenRequestBody() {
        }
        
        public DeleteTokenRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTokenResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.DeleteTokenResponseBody Body;
        
        public DeleteTokenResponse() {
        }
        
        public DeleteTokenResponse(I_Care.ServiceSSO.DeleteTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTokenResponseBody {
        
        public DeleteTokenResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUser", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAccessForUserRequestBody Body;
        
        public GetAccessForUserRequest() {
        }
        
        public GetAccessForUserRequest(I_Care.ServiceSSO.GetAccessForUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string formName;
        
        public GetAccessForUserRequestBody() {
        }
        
        public GetAccessForUserRequestBody(string username, string appName, string formName) {
            this.username = username;
            this.appName = appName;
            this.formName = formName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUserResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAccessForUserResponseBody Body;
        
        public GetAccessForUserResponse() {
        }
        
        public GetAccessForUserResponse(I_Care.ServiceSSO.GetAccessForUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessForUserResult;
        
        public GetAccessForUserResponseBody() {
        }
        
        public GetAccessForUserResponseBody(string GetAccessForUserResult) {
            this.GetAccessForUserResult = GetAccessForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(I_Care.ServiceSSO.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OdlPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserId;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string OdlPass, string NewPass, string UserId) {
            this.OdlPass = OdlPass;
            this.NewPass = NewPass;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(I_Care.ServiceSSO.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserType", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserTypeRequestBody Body;
        
        public GetUserTypeRequest() {
        }
        
        public GetUserTypeRequest(I_Care.ServiceSSO.GetUserTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        public GetUserTypeRequestBody() {
        }
        
        public GetUserTypeRequestBody(string userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTypeResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserTypeResponseBody Body;
        
        public GetUserTypeResponse() {
        }
        
        public GetUserTypeResponse(I_Care.ServiceSSO.GetUserTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserTypeResult;
        
        public GetUserTypeResponseBody() {
        }
        
        public GetUserTypeResponseBody(string GetUserTypeResult) {
            this.GetUserTypeResult = GetUserTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModul", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAllowModulRequestBody Body;
        
        public GetAllowModulRequest() {
        }
        
        public GetAllowModulRequest(I_Care.ServiceSSO.GetAllowModulRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Modul;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Access;
        
        public GetAllowModulRequestBody() {
        }
        
        public GetAllowModulRequestBody(string UserId, string Modul, int Access) {
            this.UserId = UserId;
            this.Modul = Modul;
            this.Access = Access;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModulResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAllowModulResponseBody Body;
        
        public GetAllowModulResponse() {
        }
        
        public GetAllowModulResponse(I_Care.ServiceSSO.GetAllowModulResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAllowModulResult;
        
        public GetAllowModulResponseBody() {
        }
        
        public GetAllowModulResponseBody(bool GetAllowModulResult) {
            this.GetAllowModulResult = GetAllowModulResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtend", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAccesExtendRequestBody Body;
        
        public GetAccesExtendRequest() {
        }
        
        public GetAccesExtendRequest(I_Care.ServiceSSO.GetAccesExtendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Extid;
        
        public GetAccesExtendRequestBody() {
        }
        
        public GetAccesExtendRequestBody(string UserId, int Extid) {
            this.UserId = UserId;
            this.Extid = Extid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtendResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetAccesExtendResponseBody Body;
        
        public GetAccesExtendResponse() {
        }
        
        public GetAccesExtendResponse(I_Care.ServiceSSO.GetAccesExtendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAccesExtendResult;
        
        public GetAccesExtendResponseBody() {
        }
        
        public GetAccesExtendResponseBody(bool GetAccesExtendResult) {
            this.GetAccesExtendResult = GetAccesExtendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUser", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.CheckAccGroupUserRequestBody Body;
        
        public CheckAccGroupUserRequest() {
        }
        
        public CheckAccGroupUserRequest(I_Care.ServiceSSO.CheckAccGroupUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccGroup;
        
        public CheckAccGroupUserRequestBody() {
        }
        
        public CheckAccGroupUserRequestBody(string UserId, string AccGroup) {
            this.UserId = UserId;
            this.AccGroup = AccGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUserResponse", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.CheckAccGroupUserResponseBody Body;
        
        public CheckAccGroupUserResponse() {
        }
        
        public CheckAccGroupUserResponse(I_Care.ServiceSSO.CheckAccGroupUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckAccGroupUserResult;
        
        public CheckAccGroupUserResponseBody() {
        }
        
        public CheckAccGroupUserResponseBody(bool CheckAccGroupUserResult) {
            this.CheckAccGroupUserResult = CheckAccGroupUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserUnitV2RequestBody Body;
        
        public GetUserUnitV2Request() {
        }
        
        public GetUserUnitV2Request(I_Care.ServiceSSO.GetUserUnitV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitV2RequestBody() {
        }
        
        public GetUserUnitV2RequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2Response", Namespace="SSO", Order=0)]
        public I_Care.ServiceSSO.GetUserUnitV2ResponseBody Body;
        
        public GetUserUnitV2Response() {
        }
        
        public GetUserUnitV2Response(I_Care.ServiceSSO.GetUserUnitV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitV2Result;
        
        public GetUserUnitV2ResponseBody() {
        }
        
        public GetUserUnitV2ResponseBody(string GetUserUnitV2Result) {
            this.GetUserUnitV2Result = GetUserUnitV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSOWSSoapChannel : I_Care.ServiceSSO.SSOWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSOWSSoapClient : System.ServiceModel.ClientBase<I_Care.ServiceSSO.SSOWSSoap>, I_Care.ServiceSSO.SSOWSSoap {
        
        public SSOWSSoapClient() {
        }
        
        public SSOWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSOWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.ValidateUserResponse I_Care.ServiceSSO.SSOWSSoap.ValidateUser(I_Care.ServiceSSO.ValidateUserRequest request) {
            return base.Channel.ValidateUser(request);
        }
        
        public bool ValidateUser(string username, string password) {
            I_Care.ServiceSSO.ValidateUserRequest inValue = new I_Care.ServiceSSO.ValidateUserRequest();
            inValue.Body = new I_Care.ServiceSSO.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            I_Care.ServiceSSO.ValidateUserResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).ValidateUser(inValue);
            return retVal.Body.ValidateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserResponse> I_Care.ServiceSSO.SSOWSSoap.ValidateUserAsync(I_Care.ServiceSSO.ValidateUserRequest request) {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserResponse> ValidateUserAsync(string username, string password) {
            I_Care.ServiceSSO.ValidateUserRequest inValue = new I_Care.ServiceSSO.ValidateUserRequest();
            inValue.Body = new I_Care.ServiceSSO.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).ValidateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.ValidateUserGetNIPResponse I_Care.ServiceSSO.SSOWSSoap.ValidateUserGetNIP(I_Care.ServiceSSO.ValidateUserGetNIPRequest request) {
            return base.Channel.ValidateUserGetNIP(request);
        }
        
        public I_Care.ServiceSSO.ValidateResult ValidateUserGetNIP(string username, string password) {
            I_Care.ServiceSSO.ValidateUserGetNIPRequest inValue = new I_Care.ServiceSSO.ValidateUserGetNIPRequest();
            inValue.Body = new I_Care.ServiceSSO.ValidateUserGetNIPRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            I_Care.ServiceSSO.ValidateUserGetNIPResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).ValidateUserGetNIP(inValue);
            return retVal.Body.ValidateUserGetNIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserGetNIPResponse> I_Care.ServiceSSO.SSOWSSoap.ValidateUserGetNIPAsync(I_Care.ServiceSSO.ValidateUserGetNIPRequest request) {
            return base.Channel.ValidateUserGetNIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(string username, string password) {
            I_Care.ServiceSSO.ValidateUserGetNIPRequest inValue = new I_Care.ServiceSSO.ValidateUserGetNIPRequest();
            inValue.Body = new I_Care.ServiceSSO.ValidateUserGetNIPRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).ValidateUserGetNIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.VerifyResponse I_Care.ServiceSSO.SSOWSSoap.Verify(I_Care.ServiceSSO.VerifyRequest request) {
            return base.Channel.Verify(request);
        }
        
        public bool Verify(string username, string token) {
            I_Care.ServiceSSO.VerifyRequest inValue = new I_Care.ServiceSSO.VerifyRequest();
            inValue.Body = new I_Care.ServiceSSO.VerifyRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            I_Care.ServiceSSO.VerifyResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).Verify(inValue);
            return retVal.Body.VerifyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.VerifyResponse> I_Care.ServiceSSO.SSOWSSoap.VerifyAsync(I_Care.ServiceSSO.VerifyRequest request) {
            return base.Channel.VerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.VerifyResponse> VerifyAsync(string username, string token) {
            I_Care.ServiceSSO.VerifyRequest inValue = new I_Care.ServiceSSO.VerifyRequest();
            inValue.Body = new I_Care.ServiceSSO.VerifyRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).VerifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetUserUnitResponse I_Care.ServiceSSO.SSOWSSoap.GetUserUnit(I_Care.ServiceSSO.GetUserUnitRequest request) {
            return base.Channel.GetUserUnit(request);
        }
        
        public string GetUserUnit(string username) {
            I_Care.ServiceSSO.GetUserUnitRequest inValue = new I_Care.ServiceSSO.GetUserUnitRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUserUnitRequestBody();
            inValue.Body.username = username;
            I_Care.ServiceSSO.GetUserUnitResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserUnit(inValue);
            return retVal.Body.GetUserUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitResponse> I_Care.ServiceSSO.SSOWSSoap.GetUserUnitAsync(I_Care.ServiceSSO.GetUserUnitRequest request) {
            return base.Channel.GetUserUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitResponse> GetUserUnitAsync(string username) {
            I_Care.ServiceSSO.GetUserUnitRequest inValue = new I_Care.ServiceSSO.GetUserUnitRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUserUnitRequestBody();
            inValue.Body.username = username;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetAllRolesResponse I_Care.ServiceSSO.SSOWSSoap.GetAllRoles(I_Care.ServiceSSO.GetAllRolesRequest request) {
            return base.Channel.GetAllRoles(request);
        }
        
        public I_Care.ServiceSSO.ArrayOfString GetAllRoles(string appName) {
            I_Care.ServiceSSO.GetAllRolesRequest inValue = new I_Care.ServiceSSO.GetAllRolesRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAllRolesRequestBody();
            inValue.Body.appName = appName;
            I_Care.ServiceSSO.GetAllRolesResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAllRoles(inValue);
            return retVal.Body.GetAllRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllRolesResponse> I_Care.ServiceSSO.SSOWSSoap.GetAllRolesAsync(I_Care.ServiceSSO.GetAllRolesRequest request) {
            return base.Channel.GetAllRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllRolesResponse> GetAllRolesAsync(string appName) {
            I_Care.ServiceSSO.GetAllRolesRequest inValue = new I_Care.ServiceSSO.GetAllRolesRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAllRolesRequestBody();
            inValue.Body.appName = appName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAllRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetRolesForUserResponse I_Care.ServiceSSO.SSOWSSoap.GetRolesForUser(I_Care.ServiceSSO.GetRolesForUserRequest request) {
            return base.Channel.GetRolesForUser(request);
        }
        
        public I_Care.ServiceSSO.ArrayOfString GetRolesForUser(string username, string appName) {
            I_Care.ServiceSSO.GetRolesForUserRequest inValue = new I_Care.ServiceSSO.GetRolesForUserRequest();
            inValue.Body = new I_Care.ServiceSSO.GetRolesForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            I_Care.ServiceSSO.GetRolesForUserResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetRolesForUser(inValue);
            return retVal.Body.GetRolesForUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetRolesForUserResponse> I_Care.ServiceSSO.SSOWSSoap.GetRolesForUserAsync(I_Care.ServiceSSO.GetRolesForUserRequest request) {
            return base.Channel.GetRolesForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetRolesForUserResponse> GetRolesForUserAsync(string username, string appName) {
            I_Care.ServiceSSO.GetRolesForUserRequest inValue = new I_Care.ServiceSSO.GetRolesForUserRequest();
            inValue.Body = new I_Care.ServiceSSO.GetRolesForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetRolesForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetUsersInRoleResponse I_Care.ServiceSSO.SSOWSSoap.GetUsersInRole(I_Care.ServiceSSO.GetUsersInRoleRequest request) {
            return base.Channel.GetUsersInRole(request);
        }
        
        public I_Care.ServiceSSO.ArrayOfString GetUsersInRole(string appName, string roleName) {
            I_Care.ServiceSSO.GetUsersInRoleRequest inValue = new I_Care.ServiceSSO.GetUsersInRoleRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUsersInRoleRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            I_Care.ServiceSSO.GetUsersInRoleResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUsersInRole(inValue);
            return retVal.Body.GetUsersInRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUsersInRoleResponse> I_Care.ServiceSSO.SSOWSSoap.GetUsersInRoleAsync(I_Care.ServiceSSO.GetUsersInRoleRequest request) {
            return base.Channel.GetUsersInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(string appName, string roleName) {
            I_Care.ServiceSSO.GetUsersInRoleRequest inValue = new I_Care.ServiceSSO.GetUsersInRoleRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUsersInRoleRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUsersInRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.IsUserInRoleResponse I_Care.ServiceSSO.SSOWSSoap.IsUserInRole(I_Care.ServiceSSO.IsUserInRoleRequest request) {
            return base.Channel.IsUserInRole(request);
        }
        
        public bool IsUserInRole(string username, string appName, string roleName) {
            I_Care.ServiceSSO.IsUserInRoleRequest inValue = new I_Care.ServiceSSO.IsUserInRoleRequest();
            inValue.Body = new I_Care.ServiceSSO.IsUserInRoleRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            I_Care.ServiceSSO.IsUserInRoleResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).IsUserInRole(inValue);
            return retVal.Body.IsUserInRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.IsUserInRoleResponse> I_Care.ServiceSSO.SSOWSSoap.IsUserInRoleAsync(I_Care.ServiceSSO.IsUserInRoleRequest request) {
            return base.Channel.IsUserInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.IsUserInRoleResponse> IsUserInRoleAsync(string username, string appName, string roleName) {
            I_Care.ServiceSSO.IsUserInRoleRequest inValue = new I_Care.ServiceSSO.IsUserInRoleRequest();
            inValue.Body = new I_Care.ServiceSSO.IsUserInRoleRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).IsUserInRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.RoleExistsResponse I_Care.ServiceSSO.SSOWSSoap.RoleExists(I_Care.ServiceSSO.RoleExistsRequest request) {
            return base.Channel.RoleExists(request);
        }
        
        public bool RoleExists(string appName, string roleName) {
            I_Care.ServiceSSO.RoleExistsRequest inValue = new I_Care.ServiceSSO.RoleExistsRequest();
            inValue.Body = new I_Care.ServiceSSO.RoleExistsRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            I_Care.ServiceSSO.RoleExistsResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).RoleExists(inValue);
            return retVal.Body.RoleExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.RoleExistsResponse> I_Care.ServiceSSO.SSOWSSoap.RoleExistsAsync(I_Care.ServiceSSO.RoleExistsRequest request) {
            return base.Channel.RoleExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.RoleExistsResponse> RoleExistsAsync(string appName, string roleName) {
            I_Care.ServiceSSO.RoleExistsRequest inValue = new I_Care.ServiceSSO.RoleExistsRequest();
            inValue.Body = new I_Care.ServiceSSO.RoleExistsRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).RoleExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.DeleteTokenResponse I_Care.ServiceSSO.SSOWSSoap.DeleteToken(I_Care.ServiceSSO.DeleteTokenRequest request) {
            return base.Channel.DeleteToken(request);
        }
        
        public void DeleteToken(string username) {
            I_Care.ServiceSSO.DeleteTokenRequest inValue = new I_Care.ServiceSSO.DeleteTokenRequest();
            inValue.Body = new I_Care.ServiceSSO.DeleteTokenRequestBody();
            inValue.Body.username = username;
            I_Care.ServiceSSO.DeleteTokenResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).DeleteToken(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.DeleteTokenResponse> I_Care.ServiceSSO.SSOWSSoap.DeleteTokenAsync(I_Care.ServiceSSO.DeleteTokenRequest request) {
            return base.Channel.DeleteTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.DeleteTokenResponse> DeleteTokenAsync(string username) {
            I_Care.ServiceSSO.DeleteTokenRequest inValue = new I_Care.ServiceSSO.DeleteTokenRequest();
            inValue.Body = new I_Care.ServiceSSO.DeleteTokenRequestBody();
            inValue.Body.username = username;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).DeleteTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetAccessForUserResponse I_Care.ServiceSSO.SSOWSSoap.GetAccessForUser(I_Care.ServiceSSO.GetAccessForUserRequest request) {
            return base.Channel.GetAccessForUser(request);
        }
        
        public string GetAccessForUser(string username, string appName, string formName) {
            I_Care.ServiceSSO.GetAccessForUserRequest inValue = new I_Care.ServiceSSO.GetAccessForUserRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAccessForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.formName = formName;
            I_Care.ServiceSSO.GetAccessForUserResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAccessForUser(inValue);
            return retVal.Body.GetAccessForUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccessForUserResponse> I_Care.ServiceSSO.SSOWSSoap.GetAccessForUserAsync(I_Care.ServiceSSO.GetAccessForUserRequest request) {
            return base.Channel.GetAccessForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccessForUserResponse> GetAccessForUserAsync(string username, string appName, string formName) {
            I_Care.ServiceSSO.GetAccessForUserRequest inValue = new I_Care.ServiceSSO.GetAccessForUserRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAccessForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.formName = formName;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAccessForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.ChangePasswordResponse I_Care.ServiceSSO.SSOWSSoap.ChangePassword(I_Care.ServiceSSO.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string OdlPass, string NewPass, string UserId) {
            I_Care.ServiceSSO.ChangePasswordRequest inValue = new I_Care.ServiceSSO.ChangePasswordRequest();
            inValue.Body = new I_Care.ServiceSSO.ChangePasswordRequestBody();
            inValue.Body.OdlPass = OdlPass;
            inValue.Body.NewPass = NewPass;
            inValue.Body.UserId = UserId;
            I_Care.ServiceSSO.ChangePasswordResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.ChangePasswordResponse> I_Care.ServiceSSO.SSOWSSoap.ChangePasswordAsync(I_Care.ServiceSSO.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.ChangePasswordResponse> ChangePasswordAsync(string OdlPass, string NewPass, string UserId) {
            I_Care.ServiceSSO.ChangePasswordRequest inValue = new I_Care.ServiceSSO.ChangePasswordRequest();
            inValue.Body = new I_Care.ServiceSSO.ChangePasswordRequestBody();
            inValue.Body.OdlPass = OdlPass;
            inValue.Body.NewPass = NewPass;
            inValue.Body.UserId = UserId;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetUserTypeResponse I_Care.ServiceSSO.SSOWSSoap.GetUserType(I_Care.ServiceSSO.GetUserTypeRequest request) {
            return base.Channel.GetUserType(request);
        }
        
        public string GetUserType(string userid) {
            I_Care.ServiceSSO.GetUserTypeRequest inValue = new I_Care.ServiceSSO.GetUserTypeRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUserTypeRequestBody();
            inValue.Body.userid = userid;
            I_Care.ServiceSSO.GetUserTypeResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserType(inValue);
            return retVal.Body.GetUserTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserTypeResponse> I_Care.ServiceSSO.SSOWSSoap.GetUserTypeAsync(I_Care.ServiceSSO.GetUserTypeRequest request) {
            return base.Channel.GetUserTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserTypeResponse> GetUserTypeAsync(string userid) {
            I_Care.ServiceSSO.GetUserTypeRequest inValue = new I_Care.ServiceSSO.GetUserTypeRequest();
            inValue.Body = new I_Care.ServiceSSO.GetUserTypeRequestBody();
            inValue.Body.userid = userid;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetAllowModulResponse I_Care.ServiceSSO.SSOWSSoap.GetAllowModul(I_Care.ServiceSSO.GetAllowModulRequest request) {
            return base.Channel.GetAllowModul(request);
        }
        
        public bool GetAllowModul(string UserId, string Modul, int Access) {
            I_Care.ServiceSSO.GetAllowModulRequest inValue = new I_Care.ServiceSSO.GetAllowModulRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAllowModulRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Modul = Modul;
            inValue.Body.Access = Access;
            I_Care.ServiceSSO.GetAllowModulResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAllowModul(inValue);
            return retVal.Body.GetAllowModulResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllowModulResponse> I_Care.ServiceSSO.SSOWSSoap.GetAllowModulAsync(I_Care.ServiceSSO.GetAllowModulRequest request) {
            return base.Channel.GetAllowModulAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAllowModulResponse> GetAllowModulAsync(string UserId, string Modul, int Access) {
            I_Care.ServiceSSO.GetAllowModulRequest inValue = new I_Care.ServiceSSO.GetAllowModulRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAllowModulRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Modul = Modul;
            inValue.Body.Access = Access;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAllowModulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetAccesExtendResponse I_Care.ServiceSSO.SSOWSSoap.GetAccesExtend(I_Care.ServiceSSO.GetAccesExtendRequest request) {
            return base.Channel.GetAccesExtend(request);
        }
        
        public bool GetAccesExtend(string UserId, int Extid) {
            I_Care.ServiceSSO.GetAccesExtendRequest inValue = new I_Care.ServiceSSO.GetAccesExtendRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAccesExtendRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Extid = Extid;
            I_Care.ServiceSSO.GetAccesExtendResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAccesExtend(inValue);
            return retVal.Body.GetAccesExtendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccesExtendResponse> I_Care.ServiceSSO.SSOWSSoap.GetAccesExtendAsync(I_Care.ServiceSSO.GetAccesExtendRequest request) {
            return base.Channel.GetAccesExtendAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetAccesExtendResponse> GetAccesExtendAsync(string UserId, int Extid) {
            I_Care.ServiceSSO.GetAccesExtendRequest inValue = new I_Care.ServiceSSO.GetAccesExtendRequest();
            inValue.Body = new I_Care.ServiceSSO.GetAccesExtendRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Extid = Extid;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetAccesExtendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.CheckAccGroupUserResponse I_Care.ServiceSSO.SSOWSSoap.CheckAccGroupUser(I_Care.ServiceSSO.CheckAccGroupUserRequest request) {
            return base.Channel.CheckAccGroupUser(request);
        }
        
        public bool CheckAccGroupUser(string UserId, string AccGroup) {
            I_Care.ServiceSSO.CheckAccGroupUserRequest inValue = new I_Care.ServiceSSO.CheckAccGroupUserRequest();
            inValue.Body = new I_Care.ServiceSSO.CheckAccGroupUserRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.AccGroup = AccGroup;
            I_Care.ServiceSSO.CheckAccGroupUserResponse retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).CheckAccGroupUser(inValue);
            return retVal.Body.CheckAccGroupUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.CheckAccGroupUserResponse> I_Care.ServiceSSO.SSOWSSoap.CheckAccGroupUserAsync(I_Care.ServiceSSO.CheckAccGroupUserRequest request) {
            return base.Channel.CheckAccGroupUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(string UserId, string AccGroup) {
            I_Care.ServiceSSO.CheckAccGroupUserRequest inValue = new I_Care.ServiceSSO.CheckAccGroupUserRequest();
            inValue.Body = new I_Care.ServiceSSO.CheckAccGroupUserRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.AccGroup = AccGroup;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).CheckAccGroupUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        I_Care.ServiceSSO.GetUserUnitV2Response I_Care.ServiceSSO.SSOWSSoap.GetUserUnitV2(I_Care.ServiceSSO.GetUserUnitV2Request request) {
            return base.Channel.GetUserUnitV2(request);
        }
        
        public string GetUserUnitV2(string username) {
            I_Care.ServiceSSO.GetUserUnitV2Request inValue = new I_Care.ServiceSSO.GetUserUnitV2Request();
            inValue.Body = new I_Care.ServiceSSO.GetUserUnitV2RequestBody();
            inValue.Body.username = username;
            I_Care.ServiceSSO.GetUserUnitV2Response retVal = ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserUnitV2(inValue);
            return retVal.Body.GetUserUnitV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitV2Response> I_Care.ServiceSSO.SSOWSSoap.GetUserUnitV2Async(I_Care.ServiceSSO.GetUserUnitV2Request request) {
            return base.Channel.GetUserUnitV2Async(request);
        }
        
        public System.Threading.Tasks.Task<I_Care.ServiceSSO.GetUserUnitV2Response> GetUserUnitV2Async(string username) {
            I_Care.ServiceSSO.GetUserUnitV2Request inValue = new I_Care.ServiceSSO.GetUserUnitV2Request();
            inValue.Body = new I_Care.ServiceSSO.GetUserUnitV2RequestBody();
            inValue.Body.username = username;
            return ((I_Care.ServiceSSO.SSOWSSoap)(this)).GetUserUnitV2Async(inValue);
        }
    }
}
